### ISSUE TITLE
Block changed unexpectly after explosion

### ISSUE THREAD

**Issue by yukaling** [NicoXCoding/BetterExplosions#2]
Recently I found a problem which can cause the block changed unexpectly after an explosion.
The changes seems to happening on the block which have many variants or like legacy blocks' and items' data-values.
For instance, oak has other 5 variants(birch, spruce, dark oak, acacia, jungle) but after explosion some woods or logs will be oak log
↓ Birch wood before explosion
![image](https://user-images.githubusercontent.com/73704719/230053741-a84cd049-ddfa-4010-84c0-2e3bbe12af55.png)
↓ Birch wood after explosion
![image](https://user-images.githubusercontent.com/73704719/230054052-2d50e004-dd1c-4e35-8477-1f212405b097.png)
↓ Acacia wood before explosion
![image](https://user-images.githubusercontent.com/73704719/230054243-5ab6cb82-3018-4a71-bc47-894853ee1daa.png)
↓ Acacia wood after explosion (Becoming logs)
![image](https://user-images.githubusercontent.com/73704719/230054497-a16af6bd-51d8-489e-a094-83e665496af1.png)
↓ Dark oak plank before explosion
![image](https://user-images.githubusercontent.com/73704719/230055290-26ac9545-e113-4423-9c48-df8fb85eb056.png)
↓ Dark oak plank after explosion
![image](https://user-images.githubusercontent.com/73704719/230055339-38c478d2-4e3d-4106-b783-99fd29fe6ac7.png)

Some blocks don't have explosion effects but disappeared directly, I wonder if this can be fixed?

**Comment by ynicoletti** [comment]
Hi, I fixed this in the new update.

**Comment by yukaling** [comment]
> Hi, I fixed this in the new update.

Awesome, thanks! :D
